repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff check
        args: [--fix]
      - id: ruff-format
        name: ruff format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy type check
        args: [--config-file=pyproject.toml]
        pass_filenames: false

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.391
    hooks:
      - id: pyright
        name: pyright type check
        args: [--project=pyproject.toml]
        pass_filenames: false
